[package]
name = "nom-lua53"
version = "0.0.1"
authors = ["Michael Rosenberg <42micro@gmail.com>"]
description = "A toy parser for Lua 5.3 written using nom"

[dependencies]
nom = "3.1"
libc = "0.2"
lazy_static = "0.2"

[features]
single_float = []
